# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190802_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u662f\u5546\u5bb6'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/users/%Y/%m/%d/', verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u7528\u6237\u7b49\u7ea7'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5fae\u4fe1\u53f7'),
        ),
    ]
