# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190809_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_money',
            field=models.BooleanField(default=False, verbose_name='\u8d26\u6237\u4f59\u989d'),
        ),
    ]
