# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.TextField(max_length=128, verbose_name='\u7f16\u53f7')),
                ('password', models.TextField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('pic', models.ImageField(upload_to='images/coupons/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('name', models.TextField(max_length=150, verbose_name='\u540d\u79f0')),
                ('remark', models.TextField(max_length=254, verbose_name='\u5907\u6ce8')),
                ('begin_date', models.DateTimeField(null=True, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateTimeField(null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('is_long_term', models.BooleanField(verbose_name='\u662f\u5426\u957f\u671f\u6709\u6548')),
                ('is_public', models.BooleanField(verbose_name='\u662f\u5426\u516c\u5f00')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u4ef7\u683c')),
                ('type', models.IntegerField(verbose_name='\u7c7b\u578b')),
                ('is_used', models.BooleanField(verbose_name='\u662f\u5426\u5df2\u4f7f\u7528')),
            ],
        ),
        migrations.CreateModel(
            name='CouponOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('operation_date', models.DateTimeField(auto_now=True, verbose_name='\u64cd\u4f5c\u65e5\u671f')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Coupon', verbose_name='\u4f18\u60e0\u5238')),
            ],
        ),
    ]
