# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-02 14:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponoperation',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u65b0\u62e5\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='old_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u524d\u62e5\u6709\u8005'),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='operation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_user', to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u62e5\u6709\u8005'),
        ),
    ]
