# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0003_auto_20190809_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7')),
                ('is_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='FutureCouponOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.IntegerField(verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='\u64cd\u4f5c\u65e5\u671f')),
                ('future_coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.FutureCoupon', verbose_name='\u4f18\u60e0\u5238')),
                ('new_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_new_owner_id', to=settings.AUTH_USER_MODEL, verbose_name='\u65b0\u62e5\u6709\u8005')),
                ('old_owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_old_owner_id', to=settings.AUTH_USER_MODEL, verbose_name='\u524d\u62e5\u6709\u8005')),
                ('operation_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_user_id', to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='FutureCouponOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u603b\u552e\u4ef7')),
                ('trade_date', models.DateTimeField(auto_now_add=True, verbose_name='\u4ea4\u6613\u65e5\u671f')),
                ('status', models.IntegerField(verbose_name='\u4ea4\u6613\u72b6\u6001')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_id', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to=settings.AUTH_USER_MODEL, verbose_name='\u5356\u5bb6')),
            ],
        ),
        migrations.CreateModel(
            name='FutureCouponOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7')),
                ('future_coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.FutureCoupon', verbose_name='\u671f\u8d27\u4f18\u60e0\u5238')),
                ('future_coupon_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.FutureCouponOrder', verbose_name='\u6240\u5c5e\u8ba2\u5355')),
            ],
        ),
        migrations.CreateModel(
            name='FutureCouponTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=1, max_digits=18, verbose_name='\u6298\u6263')),
                ('minimum_quote', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u6700\u4f4e\u989d\u5ea6')),
                ('issue_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u53d1\u884c\u4ef7')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7')),
                ('bing_data', models.TextField(max_length=150, verbose_name='\u7ed1\u5b9a\u6570\u636e')),
                ('now_quote', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u5f53\u524d\u989d\u5ea6')),
                ('begin_count_down_date', models.DateTimeField(verbose_name='\u671f\u8d27\u72b6\u6001\u8d77\u59cb\u65e5\u671f')),
                ('end_count_down_date', models.DateTimeField(verbose_name='\u671f\u8d27\u72b6\u6001\u7ed3\u675f\u65e5\u671f')),
                ('count', models.IntegerField(verbose_name='\u6570\u91cf')),
                ('pic', models.ImageField(upload_to='images/future-coupon-template/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('name', models.TextField(max_length=150, verbose_name='\u540d\u79f0')),
                ('remark', models.TextField(max_length=254, verbose_name='\u5907\u6ce8')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('is_long_term', models.BooleanField(verbose_name='\u662f\u5426\u957f\u671f\u6709\u6548')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantCouponTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images/coupon-template/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('name', models.TextField(max_length=150, verbose_name='\u540d\u79f0')),
                ('remark', models.TextField(max_length=254, verbose_name='\u5907\u6ce8')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('is_long_term', models.BooleanField(verbose_name='\u662f\u5426\u957f\u671f\u6709\u6548')),
                ('is_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCouponTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='images/coupon-template/%Y/%m/%d/', verbose_name='\u56fe\u7247')),
                ('name', models.TextField(max_length=150, verbose_name='\u540d\u79f0')),
                ('remark', models.TextField(max_length=254, verbose_name='\u5907\u6ce8')),
                ('begin_date', models.DateTimeField(blank=True, null=True, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65e5\u671f')),
                ('is_long_term', models.BooleanField(verbose_name='\u662f\u5426\u957f\u671f\u6709\u6548')),
                ('is_public', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7')),
                ('is_active', models.BooleanField(default=True, verbose_name='\u662f\u5426\u6fc0\u6d3b')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u62e5\u6709\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='WalletMoneyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(verbose_name='\u7c7b\u578b')),
                ('original', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u66f4\u6539\u524d\u4f59\u989d')),
                ('change', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u66f4\u6539\u91d1\u989d')),
                ('change_date', models.DateTimeField(blank=True, null=True, verbose_name='\u66f4\u6539\u65e5\u671f')),
                ('change_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_user', to=settings.AUTH_USER_MODEL, verbose_name='\u66f4\u6539\u4eba')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_money_record_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u6301\u6709\u4eba')),
            ],
        ),
        migrations.RemoveField(
            model_name='coupontemplate',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='coupontemplate',
            name='owner',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='new_owner',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='old_owner',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='operation_user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='new_owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_new_owner_id', to=settings.AUTH_USER_MODEL, verbose_name='\u65b0\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='old_owner_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_old_owner_id', to=settings.AUTH_USER_MODEL, verbose_name='\u524d\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='operation_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_user_id', to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='\u552e\u4ef7'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='head_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/merchants/%Y/%m/%d/', verbose_name='\u5934\u50cf'),
        ),
        migrations.DeleteModel(
            name='CouponTemplate',
        ),
        migrations.AddField(
            model_name='merchantcoupontemplate',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Merchant', verbose_name='\u6240\u5c5e\u5e97\u94fa'),
        ),
        migrations.AddField(
            model_name='futurecoupontemplate',
            name='merchant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Merchant', verbose_name='\u6240\u5c5e\u5e97\u94fa'),
        ),
        migrations.AddField(
            model_name='futurecoupon',
            name='futures_coupon_template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.Merchant', verbose_name='\u6240\u5c5e\u6a21\u677f'),
        ),
        migrations.AddField(
            model_name='futurecoupon',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u6301\u6709\u4eba'),
        ),
    ]
