# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupons', '0004_auto_20190817_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='futurecoupon',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='futurecouponoperation',
            old_name='future_coupon_id',
            new_name='future_coupon',
        ),
        migrations.RenameField(
            model_name='futurecouponorderdetail',
            old_name='future_coupon_id',
            new_name='future_coupon',
        ),
        migrations.RenameField(
            model_name='futurecouponorderdetail',
            old_name='future_coupon_order_id',
            new_name='future_coupon_order',
        ),
        migrations.RenameField(
            model_name='futurecoupontemplate',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='merchantcoupontemplate',
            old_name='merchant_id',
            new_name='merchant',
        ),
        migrations.RenameField(
            model_name='personalcoupontemplate',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='walletmoneyrecord',
            old_name='change_user_id',
            new_name='change_user',
        ),
        migrations.RenameField(
            model_name='walletmoneyrecord',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='create_user_id',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='new_owner_id',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='old_owner_id',
        ),
        migrations.RemoveField(
            model_name='couponoperation',
            name='operation_user_id',
        ),
        migrations.RemoveField(
            model_name='futurecouponoperation',
            name='new_owner_id',
        ),
        migrations.RemoveField(
            model_name='futurecouponoperation',
            name='old_owner_id',
        ),
        migrations.RemoveField(
            model_name='futurecouponoperation',
            name='operation_user_id',
        ),
        migrations.RemoveField(
            model_name='futurecouponorder',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='futurecouponorder',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='new_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_new_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u65b0\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='old_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_old_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u524d\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponoperation',
            name='operation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_operation_operation_user', to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecouponoperation',
            name='new_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_new_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u65b0\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecouponoperation',
            name='old_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_old_owner', to=settings.AUTH_USER_MODEL, verbose_name='\u524d\u62e5\u6709\u8005'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecouponoperation',
            name='operation_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='future_coupon_operation_operation_user', to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecouponorder',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='\u4e70\u5bb6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecouponorder',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='\u5356\u5bb6'),
            preserve_default=False,
        ),
    ]
