# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_auto_20190817_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9501\u5b9a'),
        ),
        migrations.AddField(
            model_name='futurecoupon',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u9501\u5b9a'),
        ),
    ]
